### ISSUE TITLE
which equipment are you controlling with ember+ ?

### ISSUE THREAD

**Issue by yboujraf** [jp-jp-jp/Inferno#1]
Dear @jp-jp-jp 

Which equipment are you controlling with ember+ ?

Best Regards,
Youssef

**Comment by jp-jp-jp** [comment]
This code is written just to control Glensound Infernos (
https://www.glensound.co.uk/product-details/inferno-553)

J

**Comment by yboujraf** [comment]
Dear @jp-jp-jp 

Thanks for the answer and nice job. Clear code.

Me I am using Ember+ as gateway to convert some small devices as vsmstudio expert.

Regarding your code, is bidirectional.

### Topic : Ember+ client request a change to Ember+ Server  ?

I see in your code line 24   :

```
server.on("value-change", (element, origin, orginalvalue) => {
	if (orginalvalue != element.contents.value) {
```

### Topic : Collecting status of the inferno and update the tree Ember+ ?


```
function openSocket(SA, id) {
	ws = new WebSocket("ws://" + SA + "/ppmetc", null, { handshakeTimeout: 1000 });
	ws.binaryType = "arraybuffer";
	ws.id = id
	wsconnections[ws.id] = ws;
	let i = 0
	watch = new Watchdog.Watchdog(1000, id)
	ws.onopen = function (event) {
		watch.feed(i)
		parsehttp(SA)
		parsechan(SA)
		parsechaneff(SA)
	};
	ws.onmessage = function (event) {
		i++
		watch.feed(i)
		updatews(event, SA)
		if (i == cycles) {
			i = 0
			parsehttp(SA)
			parsechan(SA)
			parsechaneff(SA)
		}
	};
	ws.onerror = function (event) {
		console.log(`Error on: ${SA} (${ips[id].name})`);
		setTimeout(function () {
			openSocket(SA, id);
		}, 10000);
	};
	watch.on('reset', () => {
		console.log(`Timeout on: ${SA} (${ips[id].name})`);
		setTimeout(function () {
			openSocket(SA, id);
		}, 10000);
	});
}

function updatews(event, SA) {
	ProcessRxData(event.data, function (wsdata) {
		updatetreewithpath(SA, `${lookup["Mic Status"]}${lookup["peak"]}`, (300 / 15) * meter)

		if (objEmberTree.getElementByPath(`${lookup[SA]}${lookup["Mic Status"]}${lookup["onair"]}`).contents.value !== onair) {
			updatetreewithpath(SA, `${lookup["Mic Status"]}${lookup["onair"]}`, onair)
		}
		else if (objEmberTree.getElementByPath(lookup[SA]).contents.rawgain != gain) {
			let element = objEmberTree.getElementByPath(lookup[SA])
			element.contents.rawgain = gain
			let res = server.getResponse(element);
			server.updateSubscribers(element.getPath(), res);
			parsehttp(SA) // Check the Mic Status hasn't changed since last check
			updategain(SA)
		}
	});
}
```

### Topic Ember+ Server update all Ember+ Client subscribers ?

But if a ember+ client is not subscribing to a path or a parameter normally the ember+ server could not update to the Ember+ Client any change ?

line 169

```
function updatetreewithpath(SA, path, value) {
	let element = objEmberTree.getElementByPath(lookup[SA] + path)
	element.contents.value = value
	let res = server.getResponse(element);
	server.updateSubscribers(element.getPath(), res);
}
```

Thanks a lot if you have time to give me up more details.

Best Regards
Youssef

**Comment by jp-jp-jp** [comment]
My code requires a forked version of the ember+ server:

https://github.com/jp-jp-jp/node-emberplus

https://github.com/evs-broadcast/node-emberplus/compare/master...jp-jp-jp:master

Where i have added 2 'additions'

The first one brings the code up-to EmBER+ spec that state that if a client
calls the entire tree, assume they also want all the children (attached is
the spec that my node now does).
The other addition allows for 'previous value' to be emitted on a value
change. Which can allow the user to do comparisons on values.

J

**Comment by yboujraf** [comment]
Dear @jp-jp-jp 

Do you get the glendsound protocol or you used wireshark ?

Best Regards,
Youssef

**Comment by jp-jp-jp** [comment]
WireShark

**Comment by yboujraf** [comment]
Good job

Do you have another device already converted in ember+?

Are you in the broadcast service ?

Best regards
Youssef
